version: "3"
services:
    web:
        build: ./web
        ports:
            - "4007:80"
            - "5432"
            - "8000"
        environment:
            POSTGRES_HOST: "0.0.0.0"
            POSTGRES_DB: notes_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pa55word
            SECRET_KEY: hard_to_guess
            BASE_URL: http://35.224.222.30:4007
            BOT_URL: http://0.0.0.0:8000
    db:
        image: postgres:latest
        environment:
            POSTGRES_HOST: "0.0.0.0"
            POSTGRES_DB: notes_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pa55word
        network_mode: service:web
    bot:
        build: ./bot
        environment:
            FLAG:  flag{N3x7_t1m3_1_w0n7_g1v3_t45k_70_Ju993rn4u7}
            BASE_URL: http://35.224.222.30:4007
        network_mode: service:web



